name: disposing_flutter
description: disposing package for flutter.
repository: https://github.com/SKKbySSK/dart_disposing/tree/master/disposing_flutter

version: 1.0.2+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  disposing: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
