name: disposing
description: A new flutter module project.
repository: https://github.com/SKKbySSK/dart_disposing

version: 1.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies:
  test: ^1.17.9
